---
latitude: 40.77989
longitude: -73.9544
map_zoom: 12
name: The Franklin Hotel
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 164 E 87th St
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10128'
_hotel_id: THE117
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
